// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbDy0o56XP-vXRYkh8Ut1oHAsOEa3c16M',
    appId: '1:132454274027:web:7842e3866b6ab868dcffae',
    messagingSenderId: '132454274027',
    projectId: 'sample-test-197eb',
    authDomain: 'sample-test-197eb.firebaseapp.com',
    storageBucket: 'sample-test-197eb.appspot.com',
    measurementId: 'G-TYP61Y5HDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCujy-o8BJlwfD16tDpzQgw7hrhaqxmYA0',
    appId: '1:132454274027:android:ed153dcf771ec295dcffae',
    messagingSenderId: '132454274027',
    projectId: 'sample-test-197eb',
    storageBucket: 'sample-test-197eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYhfV6B8Iop0zktv3UEmkjXMMW4Tp_ZYQ',
    appId: '1:132454274027:ios:945dac3597851604dcffae',
    messagingSenderId: '132454274027',
    projectId: 'sample-test-197eb',
    storageBucket: 'sample-test-197eb.appspot.com',
    iosBundleId: 'com.example.firebaseStudy',
  );
}
